name: Docker Build & Push

on:
  push:
    branches:
      - main

jobs:

    docker-push:
    uses: clouddrove/github-shared-workflows/.github/workflows/docker-build-push.yml@v2
    secrets:
      DOCKERHUB_USERNAME: # Dockerhub username
      DOCKERHUB_PASSWORD: # Dockerhub password
    with:
      registry: Dockerhub
      images: rishikkk/my-app
      IMAGE_TAG: v1