name: Docker Build & Push

on:
  push:
    branches:
      - main

jobs:
    docker-scanner:
    uses: clouddrove/github-shared-workflows/.github/workflows/docker-scanner.yml@v2


    docker-push:
    needs: docker-scanner  
    if: ${{ success() && needs.docker-scanner.result == 'success' }}   # This condition start this docker push workflow on succesfull scanning of docker image
    uses: clouddrove/github-shared-workflows/.github/workflows/docker-build-push.yml@v2
    secrets:
      DOCKERHUB_USERNAME: # Dockerhub username
      DOCKERHUB_PASSWORD: # Dockerhub password
    with:
      registry: Dockerhub
      images: rishikkk/my-app
      IMAGE_TAG: v1